# Generated by Django 4.2.19 on 2025-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='x_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
