# Generated by Django 4.2.19 on 2025-02-19 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_modules', models.PositiveIntegerField(default=0)),
                ('total_modules', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to='academics.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_course_progress',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_completed', models.BooleanField(default=False)),
                ('quiz_passed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_module_progress', to='academics.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_module_progress',
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_video_progress',
            },
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='videolecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.DeleteModel(
            name='UserQuizAttempt',
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='academics.videolecture'),
        ),
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together={('user', 'video')},
        ),
    ]
