# Generated by Django 4.2.19 on 2025-02-24 20:25

import academics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_usercourseprogress_usermoduleprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=academics.utils.video_upload_path),
        ),
    ]
