# Generated by Django 4.2.19 on 2025-02-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_duration_course_lessons_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
