# Generated by Django 4.2.19 on 2025-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_quiz_options_quiz_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='attempted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
