# Generated by Django 4.2.19 on 2025-03-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_usermoduleprogress_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
