# Generated by Django 4.2.19 on 2025-03-05 22:50

import academics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_userquizattempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='total_modules',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=academics.utils.CustomS3Storage(), upload_to=academics.utils.video_upload_path),
        ),
    ]
