# Generated by Django 4.2.19 on 2025-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_module_order_alter_quiz_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_badge',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
