# Generated by Django 4.2.19 on 2025-09-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0009_course_course_badge_course_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquizattempt",
            name="attempt_count",
            field=models.IntegerField(default=1),
        ),
    ]
